<a href="https://colab.research.google.com/github/NAGPALADITI14/Data_Mining/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)
print("Data type:", arr.dtype)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Total elements (size):", arr.size)

Array: [1 2 3 4 5]
Data type: int64
Shape: (5,)
Number of dimensions: 1
Total elements (size): 5


In [12]:
zeros_array = np.zeros((2, 3))
ones_array = np.ones((2, 3), dtype=int)
range_array = np.arange(0, 10, 2)
print("\nZeros array:\n", zeros_array)
print("Ones array:\n", ones_array)
print("Range array:", range_array)


Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones array:
 [[1 1 1]
 [1 1 1]]
Range array: [0 2 4 6 8]


In [13]:
student_name = "Aditi Nagpal"
college = "UIET"
subjects = np.array(["Math", "Physics", "Chemistry"])
marks = np.array([90, 92, 95])
print(f"\nStudent: {student_name} from {college}")
print("Subjects:", subjects)
print("Marks:", marks)
print("\nFirst subject:", subjects[0])
print("Last two subjects:", subjects[-2:])
print("First two marks:", marks[:2])
print("Last mark:", marks[-1])


Student: Aditi Nagpal from UIET
Subjects: ['Math' 'Physics' 'Chemistry']
Marks: [90 92 95]

First subject: Math
Last two subjects: ['Physics' 'Chemistry']
First two marks: [90 92]
Last mark: 95


In [14]:
bonus = 5
updated_marks = marks + bonus
print("\nMarks after adding bonus of 5:", updated_marks)


Marks after adding bonus of 5: [ 95  97 100]


In [15]:
print("\nIterating over updated marks:")
for mark in updated_marks:
  print(mark)


Iterating over updated marks:
95
97
100


In [16]:
doubled_marks = marks * 2
total_marks = marks.sum()
print("\nDoubled Marks:", doubled_marks)
print("Total Marks:", total_marks)


Doubled Marks: [180 184 190]
Total Marks: 277


In [17]:
student_scores = np.array([
[88, 92, 85],
[78, 81, 90]
])
print("\nStudent Scores:\n", student_scores)
# Calculate the average score for each subject (column-wise mean)
average_scores = student_scores.mean(axis=0)
print("Average score per subject:", average_scores)


Student Scores:
 [[88 92 85]
 [78 81 90]]
Average score per subject: [83.  86.5 87.5]
